import type { en } from './locales.ts'

/** Korean dictionary, checked complete against the English key set. */
export const ko = {
  'title': '에이전트 프리셋',
  'description': '새로 시작하는 세션에 적용됩니다. 이미 실행 중인 세션은 시작할 때 설정된 프리셋을 유지합니다.',
  'loading': '프리셋 로딩 중…',
  'error': '에이전트 프리셋을 로드할 수 없습니다.',
  'userTrust': '사용자 제공',
  'seatHint': '시작하려는 세션을 위한 에이전트 프리셋',
  'headerHint': '이 세션을 실행할 에이전트 구성이며, 세션을 시작할 때 고정됩니다',
  'nav': '에이전트 프리셋',
  'sectionIntro': '프리셋은 한 세션의 에이전트가 실행하는 플러그인 구성으로, 여기에는 도구, 프롬프트, 기능이 포함됩니다. 기존 것을 복제하여 자신만의 것으로 만들거나, 크리에이터 모드에서 에이전트가 하나를 작성하도록 하세요.',
  'builtIn': '기본 제공',
  'setDefault': '기본값으로 설정',
  'view': '보기',
  'presetStandardName': '표준 모드',
  'presetStandardDescription': '파일 편집, 셸, 파일 및 웹 검색, 스킬, 계획, 목표, 서브에이전트 및 워크플로를 갖춘 전체 코딩 에이전트.',
  'presetCodeName': '코드 모드',
  'presetCodeDescription': '모든 표준 모드 기능과 함께, 모델이 하나의 TypeScript 프로그램에서 다단계 작업을 결합할 수 있도록 Code Mode SDK를 통해 도구가 노출됩니다.',
  'presetMinimalName': '최소 모드',
  'presetMinimalDescription': '영구 bash와 str_replace_editor 도구만 사용하는 간결한 코딩 에이전트.',
  'presetCordisName': '크리에이터 모드',
  'presetCordisDescription': '사용자 지정 에이전트 프리셋을 만들기 위한 모드입니다. 모든 표준 모드 기능에 더해 런타임 검사, 플러그인 실험, 프리셋 작성 가이드를 제공합니다.',
  'duplicate': '복제',
  'duplicateUnavailable': '이 배포에는 쓰기 가능한 프리셋 디렉토리가 없습니다',
  'delete': '삭제',
  'presetId': '식별자',
  'presetIdPlaceholder': '내 에이전트',
  'displayName': '이름',
  'displayNamePlaceholder': '선택기에서 표시됨; 기본값은 식별자입니다',
  'inUse': '사용 중',
  'builtInGroup': '기본 제공',
  'customGroup': '사용자 지정',
  'noDescription': '설명 없음.',
  'brokenBadge': '로드하지 못했습니다',
  'brokenNoCopy': '로드에 실패한 프리셋은 복제할 수 없습니다',
  'copyOf': '복사 원본',
  'composition': '구성 (agent.cordis.yml)',
  'cancel': '취소',
  'close': '닫기',
  'retry': '다시 시도',
  'copyTitle': '프리셋 복제',
  'copyIntro': '이 프리셋 전체가 이 기기에 복사됩니다. 식별자는 디렉토리 이름이 되며 나중에 변경할 수 없고, 나머지 모든 것은 프리셋 자체 파일에서 편집됩니다.',
  'create': '만들기',
  'creating': '생성 중…',
  'creatorDraft': '크리에이터 모드로 맞춤 프리셋을 작성하세요',
  'openLocation': '폴더 열기',
  'showLocation': '위치 표시',
  'revealedPathLabel': '프리셋 파일:',
  'idRequired': '프리셋에 식별자를 지정하세요.',
  'idInvalid': '소문자, 숫자, 하이픈을 사용하며, 문자 또는 숫자로 시작하세요.',
  'idTaken': '이 식별자를 가진 프리셋이 이미 존재합니다.',
  'deleteTitle': '이 프리셋을 삭제하시겠습니까?',
  'deleteDescription': '프리셋 디렉터리가 삭제됩니다. 이 프리셋으로 이미 실행 중인 세션은 계속 작동하지만 새 세션에서는 선택할 수 없습니다.',
  'deleteConfirm': '삭제',
  'deleting': '삭제 중…',
} satisfies Record<keyof typeof en, string>
