import type { en } from './locales.ts'

/** Korean dictionary, checked complete against the English key set. */
export const ko = {
  'row.defineTitle': 'Cordis 플러그인 등록',
  'row.runTitle': 'Cordis 플러그인 실행',
  'row.updateTitle': 'Cordis 플러그인 업데이트',
  'row.stopTitle': 'Cordis 플러그인 중지',
  'row.removeTitle': 'Cordis 플러그인 제거',
  'purpose.missing': '(목적 없음)',
  'status.idle': '준비 완료',
  'status.awaitingApproval': '승인 대기 중',
  'status.failed': '실행 실패',
  'status.clientPending': '클라이언트 활성화 준비 완료',
  'status.running': '실행 중',
  'status.removed': '제거됨',
  'status.superseded': '새로운 실행 가능 버전이 있습니다',
  'run.removed': '이 패키지는 더 이상 존재하지 않습니다',
  'run.superseded': '아래에서 최신 실행 카드를 확인할 수 있습니다',
  'panel.hint': '실행 제어는 설정 위 Cordis 패널에서 실시간으로 사용할 수 있습니다',
  'panel.plugins.aria': 'Cordis 플러그인',
  'panel.approvals.aria': 'Cordis 승인',
  'panel.trigger': 'Cordis 플러그인',
  'panel.runningCount': '{count} 실행 중',
  'panel.title': 'Cordis 플러그인',
  'panel.empty': '아직 정의된 플러그인이 없습니다',
  'panel.loading': '읽는 중…',
  'panel.readFailed': '플러그인 인벤토리 읽기 실패: {message}',
  'panel.group.current': '이 세션',
  'panel.group.others': '다른 세션',
  'panel.version': '버전',
  'panel.current': '현재: {packageId}',
  'panel.next': '다음: {packageId}',
  'action.approve': '허용',
  'action.approveOnce': '이 버전만 허용',
  'action.approvePlugin': '이 플러그인의 향후 버전을 허용',
  'action.decline': '거절',
  'action.run': '실행',
  'action.stop': '중지',
  'action.remove': '제거',
  'action.retry': '다시 시도',
  'action.rollback': '롤백',
  'render.failedAbdicated': '{slot}에서 렌더링에 실패했습니다; 기본 UI가 복원되었습니다:',
  'render.failedHeld': '{slot}에서 렌더링 실패:',
  'a11y.defining': '플러그인 정의하기',
  'a11y.failed': '정의 실패',
  'a11y.stopped': '정의가 중단됨',
  'body.source': '플러그인 소스',
  'body.hostCode': '호스트',
  'body.clientCode': '클라이언트',
  'body.output': '결과',
  'body.copy': '복사',
  'body.copied': '복사됨',
} satisfies Record<keyof typeof en, string>
