import type { en } from './locales.ts'

/** Korean dictionary, checked complete against the English key set. */
export const ko = {
  'diagnostic.corrupt': '손상된 세션 기록',
  'diagnostic.unsupported': '지원되지 않는 서브에이전트 기록 버전',
  'diagnostic.unavailable': '세션 기록을 일시적으로 사용할 수 없습니다',
  'duration.seconds': '{seconds}s',
  'duration.minutes': '{minutes}m {seconds}s',
  'duration.hours': '{hours}h {minutes}m {seconds}s',
  'duration.days': '{days}d',
  'duration.daysHours': '{days}d {hours}h',
  'duration.months': '~{months}mo',
  'duration.monthsDays': '~{months}mo {days}d',
  'duration.years': '~{years}y',
  'duration.yearsMonths': '~{years}y {months}mo',
  'duration.exactDays': '{days}d {hours}h {minutes}m {seconds}s',
  'duration.exactTitle': '총 활성 시간: {duration}',
  'loading.label': '서브에이전트 로딩 중…',
  'loading.aria': '서브에이전트 로딩 중',
  'load.error': '서브에이전트를 불러올 수 없습니다',
  'retry': '다시 시도',
  'mode.oneShot': '원샷',
  'mode.continuable': '계속 가능',
  'activity.running': '실행 중',
  'activity.inactive': '실행되지 않음',
  'branch.collapse': '{label} 하위 항목 접기',
  'branch.expand': '{label} 하위 항목 펼치기',
  'count.total.one': '서브에이전트 {count}개',
  'count.total.other': '서브에이전트 {count}개',
  'count.running.one': '{count} 서브에이전트 실행 중',
  'count.running.other': '서브에이전트 {count}개 실행 중',
  'tree.aria': '서브에이전트 세션',
  'readonly.oneShot.title': '일회성 서브에이전트 기록',
  'readonly.title': '이 서브에이전트는 현재 읽기 전용입니다',
  'readonly.oneShot.body': '원샷 작업은 후속 조치를 허용하지 않습니다. 전체 실행 기록은 여기에서 검토하세요.',
  'readonly.body': '부모 세션이 오프라인 상태입니다. 메시지 전송을 계속하려면 다시 열어주세요.',
} satisfies Record<keyof typeof en, string>
