import type { en } from './locales.ts'

/** Korean dictionary, checked complete against the English key set. */
export const ko = {
  'nav': '모델',
  'title': '모델',
  'intro': '다음 제공자의 모델을 사용하려면 API 키를 입력하세요.',
  'edit': '편집',
  'editProvider': '{provider} 편집',
  'remove': '삭제',
  'removeProvider': '{provider} 삭제',
  'deleteTitle': '{provider}를 삭제하시겠습니까?',
  'deleteDescription': '{provider}를 삭제하면 해당 구성 설정이 제거됩니다. 이 기기에서 사용하는 자격 증명은 별도로 관리되며 유지됩니다.',
  'deleteDescriptionWithCredential': '{provider}를 삭제하면 해당 구성 및 저장된 API 키가 제거됩니다.',
  'deleteConfirm': '{provider} 삭제',
  'deleting': '{provider} 삭제 중…',
  'add': '제공자 추가',
  'provider': '제공자',
  'close': '닫기',
  'cancel': '취소',
  'apply': '적용',
  'applying': '적용 중…',
  'savedProvider': '{provider}가 저장되었습니다.',
  'credentialConfigured': 'API 키가 설정됨',
  'credentialMissing': 'API 키가 없습니다',
  'readOnly': '이 배포에서 설정 문서는 읽기 전용입니다.',
  'loadFailed': '제공자 목록을 불러오지 못했습니다',
  'conflict': '이 카드를 열어 놓은 동안 다른 사람이 이 설정을 변경했습니다. 닫았다가 다시 열어 현재 값을 수정하세요.',
  'retry': '다시 시도',
  'keyInput': 'API 키',
  'keyPlaceholder': 'API 키를 입력하세요',
  'keyPlaceholderNative': 'API 키를 입력하거나, 환경 인증을 사용하려면 비워 두세요',
  'keyStored': '구성됨 — 바꾸기 위해 새 값을 입력하세요',
  'keyEnvLocked': '실행 환경에서 제공됨(읽기 전용)',
  'customized': '맞춤 설정',
  'baseUrl': '기본 URL',
  'baseUrlDefault': '제공자 기본값',
  'models': '모델',
  'modelsInherited': '어댑터 기본값 사용',
  'modelsCustomized': '맞춤형 모델 카탈로그',
  'resetModels': '기본값 복원',
  'model': '모델',
  'modelId': '모델 ID',
  'modelName': '표시 이름',
  'modelNamePlaceholder': '비어 있을 때 모델 ID를 사용합니다',
  'contextWindow': '컨텍스트 창',
  'contextWindowPlaceholder': '제공자 기본값 사용',
  'maxTokens': '최대 출력 토큰',
  'maxTokensPlaceholder': '제공자 기본값 사용',
  'modelAdvanced': '기능',
  'addModel': '모델 추가',
  'removeModel': '모델 삭제',
  'modelsEmpty': '선택기에는 모델이 표시되지 않습니다. 목록에 없는 ID는 여전히 직접 보낼 수 있습니다.',
  'keyBlank': 'API 키를 입력하거나, 저장된 키를 유지하려면 해당 필드를 비워 두세요.',
  'keyBlankNew': 'API 키를 입력하거나, 이 제공자가 다른 방식으로 인증하는 경우 필드를 비워 두세요.',
  'keyIllegalCharacters': '이 API 키는 유효한 형식이 아닙니다. 확인해 주세요.',
  'modelIdRequired': '모델 ID가 필요합니다.',
  'modelIdDuplicate': '모델 ID는 고유해야 합니다.',
  'modelNameInvalid': '표시 이름은 비어 있을 수 없습니다.',
  'modelContextInvalid': '컨텍스트 창은 131072, 256K 또는 1M과 같은 양의 수여야 합니다.',
  'modelMaxTokensInvalid': '최대 출력 토큰 수는 8192, 64K 또는 1M과 같은 양의 숫자여야 합니다.',
  'advancedHint': '그 밖의 필드는 settings.yaml에 있습니다. 해당 섹션을 직접 편집하세요.',
  'modelCapacityInvalid': '용량은 숫자여야 하며, 선택적으로 K 또는 M이 접미사로 올 수 있습니다.',
  'modelDuplicate': '각 모델 ID는 한 번만 나타날 수 있습니다.',
  'modelContextWindow': '컨텍스트 창',
  'modelMaxTokens': '최대 출력 토큰',
  'fetchModels': '사용 가능한 모델 가져오기',
  'fetching': '제공자에서 불러오는 중…',
  'fetchNeedsBaseUrl': '먼저 기본 URL을 입력한 다음 가져오세요.',
  'fetchEmpty': '제공자가 모델을 나열하지 않았습니다. 수동으로 추가하세요.',
  'fetchTitle': '추가할 모델 선택',
  'fetchDescription': '이 제공자가 지원하는 모델입니다. 추가할 모델을 선택하세요.',
  'fetchAdopt': '선택 항목 추가',
  'customAdd': '사용자 지정 제공자 추가',
  'customTitle': '맞춤 제공자',
  'customTag': '사용자 지정',
  'customRoute': '제공자 ID',
  'customRouteHint': '요청에서 이 제공자를 고유하게 식별하며 자격 증명 이름으로도 사용되는 소문자 식별자입니다. 문자로 시작해야 합니다.',
  'customRouteInvalid': '소문자로 시작하세요; 그런 다음 소문자, 숫자, 대시를 사용하세요.',
  'customRouteTaken': '해당 ID는 이미 다른 제공자가 사용 중입니다.',
  'customDisplayName': '표시 이름',
  'customApi': 'API 프로토콜',
  'customApiUnset': '선택되지 않음',
  'customNeedsBaseUrl': '사용자 지정 제공자는 기본 URL이 필요합니다.',
  'customNeedsModels': '사용자 지정 제공자는 모델이 하나 이상 필요합니다.',
  'create': '제공자 만들기',
  'creating': '생성 중…',
  'welcomeTitle': '내부 테스트 공지',
  'welcomeBody': 'DeepSeek Harness 0.1은 현재 Harness 개발자를 위한 테스트 단계에 있습니다. 많은 영역이 추가적인 개선이 필요하며, 개발자 커뮤니티의 피드백을 환영합니다. DeepSeek Harness의 핵심 플러그인과 기본 API는 앞으로 몇 달 동안 빠르게 발전할 것입니다.\n\n우리는 전 세계 개발자들과 함께 지능의 한계를 탐구하고, 오픈소스, 개방형, 재사용 가능하며 조합 가능한 인프라를 기반으로 구축하기를 기대합니다. 전 세계의 Harness 개발자들이 DSH 플러그인 생태계에 참여하기를 환영합니다.',
  'welcomeContinue': '계속',
  'welcomeError': '승인을 저장할 수 없습니다. 다시 시도해 주세요.',
  'onboardingTitle': '시작하려면 API 키를 추가하세요',
  'onboardingDescription': '공식 DeepSeek 제공자를 설정하고 작업을 시작하세요.',
  'onboardingLater': '나중에 설정',
  'onboardingSave': '저장하고 계속',
  'onboardingSaving': '저장 중…',
  'keyRequired': '계속하려면 API 키를 입력하세요.',
} satisfies Record<keyof typeof en, string>
